### ISSUE TITLE
Path issue on generating component

### ISSUE THREAD

**Issue by jimfilippou** [Sly321/react-typescript-toolbox#3]
I generate a component on "components" directory and 
1) It creates a folder right outside components called "components\Contact\"
2) It generates 2 files right outside components folder "components\Contact\Contact.tsx" and "components\Contact\index.tsx"

Assuming it tries to use the forward slash, it won't work on Linux systems like mine. Instead it should use /path/to/component and not \path\to\component. I haven't checked out your code, I will try to fix this but I'm not 100% sure I can.

**Comment by jimfilippou** [comment]
I found the issue, look at this line below. Normally you should cross-platform check
`const folder = `${path}\\${className}\\`

**Comment by Sly321** [comment]
I added the node Path lib and use path.resolve for all path variables. You can see it in this [commit](https://github.com/Sly321/react-typescript-toolbox/commit/f708bb07278ac2693d1d0720d273b5d0a6bbb7d6).

Thanks for reporting. 👍
